"""Add game_user Association Table

Revision ID: 93b6c9baa04c
Revises: 1a1df81ea9c8
Create Date: 2025-05-24 11:01:13.559209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b6c9baa04c'
down_revision = '1a1df81ea9c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
